# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_call:
  pull_request:
    branches: [ "main", "develop" ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
        fail-fast: false
        matrix:
          # os: [ windows, macos, ubuntu ]
          node-version: [18.x]
    # concurrency: # group: ${{ github.workflow }}-${{ github.ref }}-build-${{ matrix.os }}-${{ matrix.node-version }}
    #   group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.node-version }}
    #   cancel-in-progress: true
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
    - name: Test
      uses: borales/actions-yarn@v4
      with:
        cmd: test # will run `yarn install` command


  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    needs: build-and-test
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set project name 
      run: echo "REPOSITORY_NAME=business-logic-maraffa" >> $GITHUB_ENV

    - name: Set build version
      run: echo "BUILD_VERSION=1.0.0" >> $GITHUB_ENV
      if: ${{ github.ref }} == 'refs/heads/main'
    - name: Extract tag name # Impllcit constraint the tag can be done only from release in main branch
      run: echo "TAG_NAME=${{ github.event.release.tag_name }}"
    - name: Set version with latest  
      run: echo "VERSION=latest" >> $GITHUB_ENV
      if: ${{ github.ref }} != 'refs/heads/main'
    - name: Set version with Develop
      run: echo "VERSION=develop" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:${{ env.VERSION }}  .
    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:${{ env.VERSION }} 

      #TODO not working yet
      # if: ${{ env.TAG_NAME }}
    # - name: Build Docker image
    #   run: echo "docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG_NAME }}  . "
    # - name: Push Docker image
    #   run: echo "docker push ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG_NAME }} "


  # success:
  #   runs-on: ubuntu-22.04
  #   needs:
  #     - build
  #   if: >-
  #     always() && (
  #       contains(join(needs.*.result, ','), 'failure')
  #       || !contains(join(needs.*.result, ','), 'cancelled')
  #     )
  #   steps:
  #     - name: Verify that there were no failures
  #       run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
